Add missing eslint rules
thefrontside/bigtest pull request #766
Opened 2021-01-11 10:13 UTC by dagda1

Enables the following from `@typescript-eslint/recommended`:

- `@typescript-eslint/ban-types` this mainly affects the duplicitous `{}` type that really is a top type for all non-null types.
- `@typescript-eslint/explicit-module-boundary-types`

Enabling these rules will make things a bit stricter and a bit better.

2021-01-11 23:21 UTC, cowboyd requested changes
Mostly around the operation typings which are famously confusing (and will remain so until we re-write effection in TS)

2021-01-11 23:21 UTC, cowboyd commented on packages/agent/app/agent.ts
> +import { Controller, Operation, OperationFn, Sequence } from 'effection';
Everything but `Operation` here will not make it to the next version of Effection. All effection operations should be typed as `Operation<T>` where `T` is the return value of the operation.

2021-01-11 23:21 UTC, cowboyd commented on packages/agent/app/agent.ts
> +export function* createAgent(queryParams: QueryParams): Generator<CreateAgentValue, void, Agent> {
So for example, here we would make this `Operation<Agent>`
```suggestion
export function* createAgent(queryParams: QueryParams): Operation<Agent> {
```

2021-01-11 23:21 UTC, cowboyd commented on packages/agent/app/clear-persistent-storage.ts
> +export function* clearPersistentStorage(): Generator<Generator<Operation<Context<any>>>> {
```suggestion
export function* clearPersistentStorage(): Operation<void> {
```

2021-01-11 23:21 UTC, cowboyd commented on packages/agent/app/run-lane.ts
> +export function* runLane(config: LaneConfig): Generator<RunLaneValues, void, TestImplementation> {
```suggestion
export function* runLane(config: LaneConfig): Operation<TestImplementation> {
```

2021-01-11 23:21 UTC, cowboyd commented on packages/cli/src/start-server.ts
> +export function* startServer(project: ProjectOptions, options: Options): Generator<Operation<Record<string, unknown>>> {
```suggestion
export function* startServer(project: ProjectOptions, options: Options): Operation<Record<string, unknown>> {
```

2021-01-11 23:21 UTC, cowboyd commented on packages/effection/src/mailbox.ts
> +  *pipe(other: Mailbox<T>): Generator<Operation<unknown>> {
```suggestion
  *pipe(other: Mailbox<T>): Operation<Context<void>> {
```

2021-01-11 23:21 UTC, cowboyd commented on packages/server/src/logger.ts
> +export function* createLogger({ atom, out }: LoggerOptions): Generator<Operation<Context<undefined>>> {
```suggestion
export function* createLogger({ atom, out }: LoggerOptions): Operation<void> {
```

2021-01-11 23:21 UTC, cowboyd commented on packages/server/src/result-aggregator/aggregator.ts
> +  *run(): Generator<Operation<ResultStatus>> {
```suggestion
  *run(): Operation<ResultStatus> {
```

2021-01-12 10:06 UTC, dagda1 commented
> Mostly around the operation typings which are famously confusing (and will remain so until we re-write effection in TS)

Thanks for the suggestions.  They were much simpler than mine.

2021-01-12 14:05 UTC, cowboyd commented on packages/agent/app/clear-persistent-storage.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
```suggestion
```

2021-01-12 18:37 UTC, cowboyd approved these changes
Every day, moving that code onto the guardrails.

![moving onto the rails](https://media.giphy.com/media/X9whQdPxhZsAXAhcv9/giphy.gif)

2021-01-12 19:04 UTC, merged