Add intro text to the Sample App README
thefrontside/bigtest pull request #856
Opened 2021-02-11 04:37 UTC by jenweber

## Motivation

Closes #790

## Approach

The description of BigTest is copy-pasted from the main landing page.

### Alternate Designs

n/a

### Possible Drawbacks or Risks

none. These are README-only changes.

2021-02-11 07:59 UTC, cowboyd approved these changes
😍 🚀

2021-02-11 11:09 UTC, jnicklas approved these changes

2021-02-11 16:35 UTC, minkimcello requested changes
This README won't reach people that are installing the app. I think you meant to update `./sample/app/README.md`

2021-02-12 00:30 UTC, jenweber commented
@minkimcello thanks for catching that! I updated the PR and this is ready for another review.

2021-02-12 01:33 UTC, minkimcello approved these changes

2021-02-22 09:33 UTC, merged